import titanicS from "../images/titanicScene.png";
import tita from "../images/tit.png";
import movieLogo from "../images/movieLogo.png";
import spidey from "../images/spidey.png";
import jumanji from "../images/jumanji.png";
import wolf from "../images/wolf.png";
import mrs from "../images/mrs.png";
import hob from "../images/hob.png";
import spideyLogo from "../images/spideyLogo.png";
import spideyScene from "../images/spideyScene.png";
import moralis from "../images/moralis.png";
import moralisLogo from "../images/moralisLogo.png";
import moralisScene from "../images/moralisScene.png";
import jam from "../images/jam.png";
import jamLogo from "../images/jamLogo.png";
import jamScene from "../images/jamScene.png";
import bayw from "../images/bayw.png";
import shrek from "../images/shrek.png";
import lucy from "../images/lucy.png";
import topgu from "../images/topgu.png";
import imit from "../images/imit.png";
import reven from "../images/reven.png";
import tomb from "../images/tomb.png";
import amaz from "../images/amaz.png";
import bigs from "../images/bigs.png";
import secona from "../images/secona.png";
import ted from "../images/ted.png";
import amerp from "../images/amerp.png";

export const movies = [
  {
    Movie: "https://gdurl.com/aHER",
    Thumnbnail: tita,
    Scene: titanicS,
    Logo: movieLogo,
    Name: "Caballero Águila",
    Description: "Upon finishing high school, three friends must choose the path their lives will take. Pastor dreams of flying and the love of Flor, the sister of a jealous Nacho, who will look for an easy way out by enlisting in the ranks of crime.",
    Genre: "Action-Adventure, Drama",
    //Director: "Alejandro Blázquez de Nicolás",
    Actors: "Luis Alberti, María Cid",
    Year: "2022",
    Duration: "98 min",
  },
  {
    Movie: "https://doc-14-54-docs.googleusercontent.com/docs/securesc/6oa92t007hi3eeeff1e3t9e9dogg67on/23msjv7q9hi3iiqglcroc6ni91opnvj5/1653155775000/07065784338711130298/15573714808516402618/1NR30b4P4nRH8iCrqZf12uFJevUre3qhN?ax=ACxEAsZ3Acsgq05MvPQwms5bX1wfq6O0CzZf63PBKIbdRJCM8S25g34jgAdFV7wWCPfRpaCRN-6CWI0JyTIIxfjiOO471MUnV4PXBLOP0EJm5yJD-Xa5CU-liKkqsM_RqS6KleomDuFnerzMwfPKHV6g8ape803g48McpFqHyinM1Olnviy-ggesXv1W2CMESBAD7tatzoYQbg8s4jhf90hHYAgylX_O4aIxFqjab0sqFTEjWBe6E62GtWIiUlbBe_ZHtsC0BFEs4Ip1qxd0sbP5VDYjNWafUpE6ecpJ1gy3V3LVuArUw_FuA0gNL9NZdKLC1mVA5BhdC-22Zh6vwpaAP6B1-RW9F9FSln_ghST2XZoA-RGhI1zKJEPELcYSW8OjUzgyafLPpQDDnl8QFSlAkqtAkLduB0SgmIOQTsL-yZowmZ_C8xGa84D3ZoHi8y3K9zAauKkuvBbVTM3jb2FrLwvvuqDjTQzGMnpvHHXUBsluQombvySLliYg8bctFRQtR_uZASLGfZ-J-M1xdSYjNcW-tEw9FjzKCvSU4y1yEc5hXbj4kjss9e0lIWPyXMdDuWSN7VxzWCgFph25VsIA26abepzV4StfEADdqd0cwPX2EbQgivDZApffM7su6pD_vsl__FtmRo0O8c0_d25xmcLR4gdzUVFYZugPdxVsPsQu2aAsKjpkAgKLkbxw48ld9OF02N27AjDsNpwyJuWlhblKhS1z2Mq76_BlKa6_XTAKr1ehVzhi9uRrZCpFCcaVTYqpXuH3Li8UGPibPy7STTl2CRPvFaE7eBz5hKGgyn1wLpVIQttYe-3Re2rpytTIrRbmaFuU-9gzlVbzOSQxO_9Lu5pcRdPfTUpHQbx31UQY-_Q8okXwZqeHiH63Bph63PcaK1tDbt4MsfwotQ3QYb6OouJPVGM4dl7Ze_22ZP_H4iGTv17uc2sw871AywHVXR_EQ-b9nj_hlF0QWi28sL_Ude_NXCyeiyxTyf-gRPMGOC64D_tZoI5HCx2QqEqKcLt6NjnJd1M&authuser=0&nonce=oou3tpst5ru7o&user=15573714808516402618&hash=brlh0i2f184vraa2qo133umu61uru6lo",
    Thumnbnail: spidey,
    Scene: spideyScene,
    Logo: spideyLogo,
    Name: "El Fantástico Mundo de Juan Orol",
    Description: "The film freely narrates the biography of one of the icons in the history of Mexican cinema: Juan Orol, a man of Galician origin who, after various adventures, arrived in Mexico to become, involuntarily, the creator of several cinematographic genres, among which the Rumberas Cinema and the Gangster Cinema stand out, obtaining enormous success at the box office but with terrible reviews. He became known as the involuntary surrealist.",
    Genre: "Black-Comedy, Biopic",
    Actors: "Roberto Sosa, Ximena Rubio, Gabriela de la Garza",
    Year: "2012",
    Duration: "94 min",
  },
  {
    Movie: "https://doc-0g-54-docs.googleusercontent.com/docs/securesc/6oa92t007hi3eeeff1e3t9e9dogg67on/445m31in0tj61gek7ed9u3dd1jejf3tf/1653156000000/07065784338711130298/15573714808516402618/15P3g8oyX5_H8pEaIY_QsfOE_oo-qC7oC?ax=ACxEAsb9gJFdfl0_a-3d8SDQu8ou7qGREh46KjoVh6u6oUxPmTW-f6MB-QuMGVGyaVRsLtJrJV9A6YxchfvI5hUA0d6FTTrqxSIZaiFzDgCVEn_qu-31DBWGhaQJ83MtCz6vqfYA4vsIgozv7gZuuXY8UPGRAZKGw8x-H-bUfxRDAm2sFS170I7vZ959LNEiW7NVcoEKxzz75P5JMwwBFmA0_2ne5zTCBtuqoZRKvgKtoj_LvfFYHm4Cyy4RtyHOrxWUOb9vTRp469pSkeWNidGTLaEPTN8NP7zhfBHKroBJMjvWMFScL06_-V-1XSwCi80oXHVQYItSPe6N_mkmWRiXy84q96WJVIw_HEOFVa9YBhEDG1R5w7Snar_fsSPd9GBgAxnH8-ATfQqjH9cKwVsZ-YRzrw44wJo1WZJ_uokiavg0l5iCMMC4j8GRF5hwBdVkzTQ_H1SuEJiwd47JAVMOCFcxYXMSdjlLY_NY9714xOinjTPlbvRVH0Vr8AW3cLQdGbcIqLsZbGxK_lVmdqXc5dEQ4adkEwqNjx0NASRctEi-rYvgl7Kf7vJtk0YqTslK2AXaKg-LTjJSMypVVi0A4mr4liJcxzNpZQ9ZE9OOgrWtgzgL60oC8V4ogaRCIkVn2Twf4qZujqtItg9IFfIT2Ji3Jk2W9boQpIcHpCXiUrem2Jr-F1MlZmvMGa9w6EhqB16h8CDYNNYVVI3mnC5eV4ZWCk3lwbHlmPDVwaUHVeeUUdDu7-BFb9Wj9pKro0QZwKlOvrvPPRj76ibfibwsjBQvyD1yb6fUngaXRWKuBvf0qBDZCKt2YL7EEe7EinTWdyp0ohhK1aNNjVhbzkmqjdydR8ptTLm-UO330kEn9xXBPjqAhzy7407gpkszQsqagDReexY5JLXhBQoGIg-C2YVi2n6ZKyPr1MLaJV9gWo2lmtRR54E0dsqepjP0covxktOH_82vO6Tb5diTV6uxf5yU4L9IQO9lKj6UyiazjbO0c55vIia_Z0J2tweA9vrsvrwjL5FoTcc&authuser=0",
    Thumnbnail: jumanji,
    Scene: jumanji,
    Logo: "",
    Name: "Tiempos Felices",
    Description: "Max is a young man who, fed up with his relationship, has tried everything to break up with his girlfriend, but he can't do it. Desperate, he hires the services of a breakup agency, only to discover that there is no perfect solution.",
    Genre: "Comedy",
    Actors: "Cassandra Ciangherotti, Luis Arrieta",
    Year: "2015",
    Duration: "88 min",
  },
  {
    Movie: "https://drive.google.com/file/d/1sJD2Jhstn-dGKEdOfGeEW_BCHnsIf8Vi/view",
    Thumnbnail: moralis,
    Scene: moralisScene,
    Logo: "",
    Name: "Mai Morire",
    Description: "Chayo returns to Xochimilco to care for her elderly mother, but the comfort of traditional life makes her choose a marriage that will make her abandon her ideals. Her particular perceptions and her absolute faith in life will force her to commit the greatest sacrifice a mother can make.",
    Genre: "Rural Drama",
    Actors: "Margarita Saldaña, Amalia Salas, Juan Chirinos",
    Year: "2012",
    Duration: "89 min",
  },
  {
    Movie: "",
    Thumnbnail: wolf,
    Scene: wolf,
    Logo: "",
    Name: "Los Muertos",
    Description: "A weekend in the lives of five wealthy young people, whose common characteristic is apathy and excess, is interrupted by the momentary appearance of national violence and the accidental death of one of its members.",
    Genre: "Drama",
    Actors: "Elena Larrea, Ignacio Beteta, Santiago Corcuera",
    Year: "2014",
    Duration: "89 min",
  },
  {
    Movie: "",
    Thumnbnail: mrs,
    Scene: mrs,
    Logo: "",
    Name: "Táu",
    Description: "Táu is the story of Gustavo (Brontis Jodorowsky), a man who travels to the Wirikuta desert, where he will confront his deepest pain.",
    Genre: "Drama",
    Actors: "Brontis Jodorowsky, Mariana Gonzaléz",
    Year: "2012",
    Duration: "80 min",
  },
  {
    Movie: "",
    Thumnbnail: jam,
    Scene: jamScene,
    Logo: "",
    Name: "La Noche Asturiana",
    Description: "Dirección / Diego Graue, Música original / Pablo Acevedo, Productor / Juan Sarquis, Fotografía / Felipe Perez Bouchard, Productora /Filmaciones de la Ciudad.",
    Genre: "Drama",
    Actors: "Rene Reyes, Mau Escobar",
    Year: "2015",
    Duration: "145 min",
  },
  {
    Movie: "",
    Thumnbnail: hob,
    Scene: hob,
    Logo: "",
    Name: "Fogo",
    Description: "An unknown phenomenon threatens the lives of the rural community of Fogo, located on a small island in the region of Newfoundland, Canada. It has already been almost completely abandoned. Although the chances of surviving there are slim, some residents cling to the place.",
    Genre: "Drama, Documental",
    Actors: "Norman Foley, Ron Broders, Joseph Dwyer",
    Year: "2012",
    Duration: "61 min",
  },
  {
    Movie: "",
    Thumnbnail: shrek,
    Scene: shrek,
    Logo: "",
    Name: "Verlo en Domingo",
    Description: "After a night of drinking a city dweller - Domingo- is caught in a fight with the neighborhoods mechanic. Therefore he decides to avoid problems through his escape, and makes his way to Acapulco Bay; this being his first adventure away from Mexico city. On the road to the beach, he will meet a woman who will make him choose between fulfilling their love or his dream to see the sea for the first time.",
    Genre: "Adventure, Drama, Romance",
    Actors: "Ramon Álvarez, Mireille Anaya",
    Year: "2009",
    Duration: "16 min",
  },
  {
    Movie: "",
    Thumnbnail: reven,
    Scene: reven,
    Logo: "",
    Name: "Ready or Not",
    Description: "Four college buddies find themselves on the adventure of their lives, when on the morning after a Las Vegas bachelor party, they end up stranded deep in Mexico penniless, being chased, falling in love, and fighting to make it back across the border in time for the wedding.",
    Genre: "Comedy",
    Actors: "Christian Oliver, Seamus Dever, Evan Helmuth",
    Year: "2009",
    Duration: "88 min",
  },
  {
    Movie: "",
    Thumnbnail: imit,
    Scene: imit,
    Logo: "",
    Name: "Recto Recto Gancho",
    Description: "The legendary 'Faraonica San Juan Boxing Arena' is once again the scenario for an epic encounter, this time between 'Choko' Tabarez and 'Duvalin' Espadas. Everything seems to be ready to enjoy round after round of pugilist talent, when all of a sudden, an unexpected uppercut changes the outcome of the fight and the course of the night for all those present.",
    Genre: "Short, Action, Comedy, Sport",
    Actors: "Marco Aurelio, Alejandro Blázquez, Alfonso Borbolla",
    Year: "2010",
    Duration: "11 min",
  },
  {
    Movie: "",
    Thumnbnail: topgu,
    Scene: topgu,
    Logo: "",
    Name: "Los Últimos",
    Description: "Dirección: Santiago Fábregas, Producción: Mariana Rodríguez Cabarga y Gabriel Stavenhagen, Fotografía: Ximena del Valle, Diseño Sonoro: Enrique Domínguez, Edición: Branko Gómez- Palacio, Dirección de Arte: Pedro Pablo Etienne, Música: Raúl Vizzi",
    Genre: "Short Film",
    Actors: "n/a",
    Year: "2012",
    Duration: "14 min",
  },
  {
    Movie: "",
    Thumnbnail: lucy,
    Scene: lucy,
    Logo: "",
    Name: "Y tu mamá también",
    Description: "In Mexico, two teenage boys and an attractive older woman embark on a road trip and learn a thing or two about life, friendship, sex, and each other.",
    Genre: "Drama",
    Actors: "Maribel Verdú, Gael García Bernal, Diego Luna",
    Year: "2001",
    Duration: "106 min",
  },
  {
    Movie: "",
    Thumnbnail: bayw,
    Scene: bayw,
    Logo: "",
    Name: "Ya no estoy aquí",
    Description: "In Monterrey, Mexico, a young street gang spends their days dancing to slowed-down cumbia and attending parties. After a mix-up with a local cartel, their leader is forced to migrate to the U.S. but quickly longs to return home.",
    Genre: "Drama",
    Actors: "Juan Daniel García Treviño, Xueming Angelina Chen, Sophia Metcalf",
    Year: "2019",
    Duration: "112 min",
  },
  {
    Movie: "",
    Thumnbnail: tomb,
    Scene: tomb,
    Logo: "",
    Name: "Los de abajo",
    Description: "Mexican author Mariano Azuela's novel about a peasant who joins a group of rebels who fight in the Mexican Revolution.",
    Genre: "Drama / World Cinema",
    Actors: "Eric del Castillo, Enrique Lucero",
    Year: "1978",
    Duration: "115 min",
  },
  {
    Movie: "",
    Thumnbnail: amaz,
    Scene: amaz,
    Logo: "",
    Name: "Tempestad",
    Description: "A documentary film about the unspeakable abyss in the lives of two women, one deprived of her liberty and the other marked by the absence of her disappeared daughter. Through images that immerse us in a journey from north to south in Mexico, the testimonies of Miriam and Adela configure a reality where violence has taken control of our lives, our desires and dreams.",
    Genre: "Documentary",
    Actors: "Miriam Carvajal y Adela Alvarado",
    Year: "2016",
    Duration: "105 min",
  },
  {
    Movie: "",
    Thumnbnail: bigs,
    Scene: bigs,
    Logo: "",
    Name: "Gueros",
    Description: "Tomas is too much for his lone mother so she sends him to live with his older brother Federico, aka Sombra, in Mexico City.",
    Genre: "Comedy, Drama",
    Actors: "Tenoch Huerta, Sebastián Aguirre, Ilse Salas",
    Year: "2014",
    Duration: "106 min",
  },
  {
    Movie: "",
    Thumnbnail: secona,
    Scene: secona,
    Logo: "",
    Name: "Desierto",
    Description: "A group of people trying to cross the border from Mexico into the United States encounter a racist man who has taken border patrol duties into his own hands.",
    Genre: "Action, Adventure, Thriller",
    Actors: "Gael García Bernal, Jeffrey Dean Morgan, Alondra Hidalgo ",
    Year: "2015",
    Duration: "88 min",
  },
  {
    Movie: "",
    Thumnbnail: ted,
    Scene: ted,
    Logo: "",
    Name: "Entre Vivas y Alabados: La fiesta grande de Chapa de Corso",
    Description: "Documentary that explores the tradition and its meanings within the great festival of January in Chiapa de Corso, a beautiful town on the banks of the Grijalba River, at the gate of the Sump Canyon, in the state of Chiapas. A waste of joy, color and celebration accompanied by the traditional music of the region and the unmistakable dances of the Parachico and the Chunta.",
    Genre: "Documentary",
    Actors: "n/a",
    Year: "2012",
    Duration: "n/a",
  },
  {
    Movie: "",
    Thumnbnail: amerp,
    Scene: amerp,
    Logo: "",
    Name: "Después de Lucía",
    Description: "Alejandra and her dad Roberto have just moved to town. She is new at school, he has a new job. Starting over is sometimes complicated when you have left so much behind.",
    Genre: "Drama",
    Actors: "Tessa Ia, Hernán Mendoza, Gonzalo Vega Jr.",
    Year: "2012",
    Duration: "103 min",
  },
];
